USE ROLE SYSADMIN;

CREATE WAREHOUSE KAFKA_CONNECT WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;

USE WAREHOUSE KAFKA_CONNECT;

CREATE DATABASE XNODE_DB;

USE DATABASE XNODE_DB;

CREATE SCHEMA XNODE_SCHEMA;

USE ROLE SECURITYADMIN;
CREATE ROLE KAFKA_CONNECT_XNODE_ROLE;

GRANT USAGE ON WAREHOUSE KAFKA_CONNECT TO ROLE KAFKA_CONNECT_XNODE_ROLE;

GRANT USAGE ON DATABASE XNODE_DB TO ROLE KAFKA_CONNECT_XNODE_ROLE;

USE ROLE SYSADMIN;
USE WAREHOUSE KAFKA_CONNECT;
USE DATABASE XNODE_DB;

GRANT USAGE ON SCHEMA XNODE_SCHEMA TO ROLE KAFKA_CONNECT_XNODE_ROLE;

GRANT CREATE TABLE ON SCHEMA XNODE_SCHEMA TO ROLE KAFKA_CONNECT_XNODE_ROLE;

GRANT CREATE STAGE ON SCHEMA XNODE_SCHEMA TO ROLE KAFKA_CONNECT_XNODE_ROLE;

GRANT CREATE PIPE ON SCHEMA XNODE_SCHEMA TO ROLE KAFKA_CONNECT_XNODE_ROLE;

USE ROLE SECURITYADMIN;

CREATE USER XNODE_CONNECT_USER 
  PASSWORD = 'Xnode-Develop'
  DEFAULT_WAREHOUSE = 'KAFKA_CONNECT'
  DEFAULT_NAMESPACE = 'XNODE_DB.XNODE_SCHEMA'
  RSA_PUBLIC_KEY = CONNECT_USER_KEY
  DEFAULT_ROLE = 'KAFKA_CONNECT_XNODE_ROLE';
  
GRANT ROLE KAFKA_CONNECT_XNODE_ROLE TO USER XNODE_CONNECT_USER;
